export const navigation = [
  {
    key: 'foundation',
    title: 'Fundação',
    items: [
      { name: 'Tokens de Design', href: '/styleguide' },
    ],
  },
  {
    key: 'general',
    title: 'Geral',
    items: [
      { name: 'Button',      href: '/styleguide/components/button' },
      { name: 'FloatButton', href: '/styleguide/components/floatbutton' },
      { name: 'Icon',        href: '/styleguide/components/icon' },
      { name: 'Typography',  href: '/styleguide/components/typography' },
    ],
  },
  {
    key: 'layout',
    title: 'Layout',
    items: [
      { name: 'Divider', href: '/styleguide/components/divider' },
      { name: 'Grid',    href: '/styleguide/components/grid' },
      { name: 'Layout',  href: '/styleguide/components/layout' },
      { name: 'Space',   href: '/styleguide/components/space' },
    ],
  },
  {
    key: 'navigation',
    title: 'Navegação',
    items: [
      { name: 'Anchor',     href: '/styleguide/components/anchor' },
      { name: 'Breadcrumb', href: '/styleguide/components/breadcrumb' },
      { name: 'Dropdown',   href: '/styleguide/components/dropdown' },
      { name: 'Menu',       href: '/styleguide/components/menu' },
      { name: 'Pagination', href: '/styleguide/components/pagination' },
      { name: 'Steps',      href: '/styleguide/components/steps' },
    ],
  },
  {
    key: 'data-entry',
    title: 'Entrada de Dados',
    items: [
      { name: 'AutoComplete', href: '/styleguide/components/autocomplete' },
      { name: 'Cascader',     href: '/styleguide/components/cascader' },
      { name: 'Checkbox',     href: '/styleguide/components/checkbox' },
      { name: 'ColorPicker',  href: '/styleguide/components/colorpicker' },
      { name: 'DatePicker',   href: '/styleguide/components/datepicker' },
      { name: 'Form',         href: '/styleguide/components/form' },
      { name: 'Input',        href: '/styleguide/components/input' },
      { name: 'InputNumber',  href: '/styleguide/components/inputnumber' },
      { name: 'Mentions',     href: '/styleguide/components/mentions' },
      { name: 'Radio',        href: '/styleguide/components/radio' },
      { name: 'Rate',         href: '/styleguide/components/rate' },
      { name: 'Select',       href: '/styleguide/components/select' },
      { name: 'Slider',       href: '/styleguide/components/slider' },
      { name: 'Switch',       href: '/styleguide/components/switch' },
      { name: 'TimePicker',   href: '/styleguide/components/timepicker' },
      { name: 'Transfer',     href: '/styleguide/components/transfer' },
      { name: 'TreeSelect',   href: '/styleguide/components/treeselect' },
      { name: 'Upload',       href: '/styleguide/components/upload' },
    ],
  },
  {
    key: 'data-display',
    title: 'Exibição de Dados',
    items: [
      { name: 'Avatar',       href: '/styleguide/components/avatar' },
      { name: 'Badge',        href: '/styleguide/components/badge' },
      { name: 'Calendar',     href: '/styleguide/components/calendar' },
      { name: 'Card',         href: '/styleguide/components/card' },
      { name: 'Carousel',     href: '/styleguide/components/carousel' },
      { name: 'Collapse',     href: '/styleguide/components/collapse' },
      { name: 'Descriptions', href: '/styleguide/components/descriptions' },
      { name: 'Empty',        href: '/styleguide/components/empty' },
      { name: 'Image',        href: '/styleguide/components/image' },
      { name: 'List',         href: '/styleguide/components/list' },
      { name: 'Popover',      href: '/styleguide/components/popover' },
      { name: 'QRCode',       href: '/styleguide/components/qrcode' },
      { name: 'Statistic',    href: '/styleguide/components/statistic' },
      { name: 'Table',        href: '/styleguide/components/table' },
      { name: 'Tabs',         href: '/styleguide/components/tabs' },
      { name: 'Tag',          href: '/styleguide/components/tag' },
      { name: 'Timeline',     href: '/styleguide/components/timeline' },
      { name: 'Tooltip',      href: '/styleguide/components/tooltip' },
      { name: 'Tour',         href: '/styleguide/components/tour' },
      { name: 'Tree',         href: '/styleguide/components/tree' },
    ],
  },
  {
    key: 'feedback',
    title: 'Feedback',
    items: [
      { name: 'Alert',        href: '/styleguide/components/alert' },
      { name: 'Drawer',       href: '/styleguide/components/drawer' },
      { name: 'Message',      href: '/styleguide/components/message' },
      { name: 'Modal',        href: '/styleguide/components/modal' },
      { name: 'Notification', href: '/styleguide/components/notification' },
      { name: 'Popconfirm',   href: '/styleguide/components/popconfirm' },
      { name: 'Progress',     href: '/styleguide/components/progress' },
      { name: 'Result',       href: '/styleguide/components/result' },
      { name: 'Skeleton',     href: '/styleguide/components/skeleton' },
      { name: 'Spin',         href: '/styleguide/components/spin' },
      { name: 'Watermark',    href: '/styleguide/components/watermark' },
    ],
  },
]
